#############################################################################
# Makefile for building: HomeworkCheckerGUI.app/Contents/MacOS/HomeworkCheckerGUI
# Generated by qmake (3.1) (Qt 6.1.0)
# Project:  HomeworkCheckerGUI.pro
# Template: app
# Command: /Users/linsixing/Qt/6.1.0/clang_64/bin/qmake -o HomeworkCheckerGUI.xcodeproj/project.pbxproj HomeworkCheckerGUI.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/linsixing/Qt/6.1.0/clang_64/bin/qmake
HomeworkCheckerGUI.xcodeproj/project.pbxproj: HomeworkCheckerGUI.pro ../../../Qt/6.1.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/6.1.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/unix.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/mac.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/macx.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/clang.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/qconfig.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core5compat.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachine.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.1.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/macx-xcode/qmake.conf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/6.1.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/qt.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/resources_functions.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/resources.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/moc.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/6.1.0/clang_64/mkspecs/features/lex.prf \
		HomeworkCheckerGUI.pro \
		qml.qrc \
		../../../Qt/6.1.0/clang_64/lib/QtQuick.framework/Resources/QtQuick.prl \
		../../../Qt/6.1.0/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../../Qt/6.1.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.1.0/clang_64/lib/QtQmlModels.framework/Resources/QtQmlModels.prl \
		../../../Qt/6.1.0/clang_64/lib/QtQml.framework/Resources/QtQml.prl \
		../../../Qt/6.1.0/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../../Qt/6.1.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o HomeworkCheckerGUI.xcodeproj/project.pbxproj HomeworkCheckerGUI.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
../../../Qt/6.1.0/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/device_config.prf:
../../../Qt/6.1.0/clang_64/mkspecs/common/unix.conf:
../../../Qt/6.1.0/clang_64/mkspecs/common/mac.conf:
../../../Qt/6.1.0/clang_64/mkspecs/common/macx.conf:
../../../Qt/6.1.0/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/6.1.0/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/6.1.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.1.0/clang_64/mkspecs/common/clang.conf:
../../../Qt/6.1.0/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/6.1.0/clang_64/mkspecs/qconfig.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core5compat.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core5compat_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxmlqml.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_shadertools.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachine.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachine_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachineqml.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.1.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.1.0/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/6.1.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.1.0/clang_64/mkspecs/macx-xcode/qmake.conf:
../../../Qt/6.1.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/6.1.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/default_post.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/mac.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/qt.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/resources_functions.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/resources.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/moc.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/yacc.prf:
../../../Qt/6.1.0/clang_64/mkspecs/features/lex.prf:
HomeworkCheckerGUI.pro:
qml.qrc:
../../../Qt/6.1.0/clang_64/lib/QtQuick.framework/Resources/QtQuick.prl:
../../../Qt/6.1.0/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../../Qt/6.1.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.1.0/clang_64/lib/QtQmlModels.framework/Resources/QtQmlModels.prl:
../../../Qt/6.1.0/clang_64/lib/QtQml.framework/Resources/QtQml.prl:
../../../Qt/6.1.0/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../../Qt/6.1.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o HomeworkCheckerGUI.xcodeproj/project.pbxproj HomeworkCheckerGUI.pro -spec macx-xcode

qmake_all: FORCE

